INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'INTJ', 90, '충돌 가능성 있음', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'INTP', 60, '의외의 조합', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ENTJ', 79, '서로 배울 수 있는 관계', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ENTP', 66, '환상의 궁합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'INFJ', 61, '감정적으로 잘 통함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'INFP', 81, '파격적인 시너지', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ENFJ', 72, '안정적인 관계', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ENFP', 54, '서로를 자극함', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ISTJ', 89, '서로를 자극함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ISFJ', 90, '대화가 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ESTJ', 78, '대화가 잘 통함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ESFJ', 67, '안정적인 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ISTP', 51, '서로를 자극함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ISFP', 52, '서로를 자극함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ESTP', 74, '서로를 자극함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTJ', 'ESFP', 98, '충돌 가능성 있음', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'INTJ', 66, '대화가 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'INTP', 76, '대화가 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ENTJ', 82, '환상의 궁합', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ENTP', 92, '안정적인 관계', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'INFJ', 89, '의외의 조합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'INFP', 78, '충돌 가능성 있음', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ENFJ', 57, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ENFP', 48, '대화가 잘 통함', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ISTJ', 62, '충돌 가능성 있음', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ISFJ', 72, '정반대의 매력', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ESTJ', 78, '대화가 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ESFJ', 47, '충돌 가능성 있음', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ISTP', 69, '충돌 가능성 있음', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ISFP', 47, '충돌 가능성 있음', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ESTP', 78, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INTP', 'ESFP', 82, '충돌 가능성 있음', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'INTJ', 95, '서로 배울 수 있는 관계', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'INTP', 50, '대화가 잘 통함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ENTJ', 68, '서로 배울 수 있는 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ENTP', 41, '충돌 가능성 있음', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'INFJ', 80, '서로를 자극함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'INFP', 82, '서로 배울 수 있는 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ENFJ', 65, '파격적인 시너지', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ENFP', 96, '충돌 가능성 있음', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ISTJ', 69, '감정적으로 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ISFJ', 98, '정반대의 매력', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ESTJ', 40, '충돌 가능성 있음', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ESFJ', 83, '감정적으로 잘 통함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ISTP', 86, '의외의 조합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ISFP', 65, '서로를 자극함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ESTP', 77, '충돌 가능성 있음', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTJ', 'ESFP', 45, '충돌 가능성 있음', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'INTJ', 91, '감정적으로 잘 통함', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'INTP', 99, '환상의 궁합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ENTJ', 83, '파격적인 시너지', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ENTP', 54, '정반대의 매력', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'INFJ', 59, '파격적인 시너지', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'INFP', 61, '환상의 궁합', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ENFJ', 76, '감정적으로 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ENFP', 42, '대화가 잘 통함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ISTJ', 97, '파격적인 시너지', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ISFJ', 83, '충돌 가능성 있음', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ESTJ', 61, '환상의 궁합', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ESFJ', 52, '대화가 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ISTP', 95, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ISFP', 63, '서로를 자극함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ESTP', 58, '서로 배울 수 있는 관계', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENTP', 'ESFP', 70, '파격적인 시너지', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'INTJ', 99, '환상의 궁합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'INTP', 99, '충돌 가능성 있음', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ENTJ', 57, '정반대의 매력', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ENTP', 80, '의외의 조합', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'INFJ', 92, '환상의 궁합', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'INFP', 94, '대화가 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ENFJ', 87, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ENFP', 80, '의외의 조합', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ISTJ', 65, '감정적으로 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ISFJ', 80, '안정적인 관계', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ESTJ', 52, '의외의 조합', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ESFJ', 58, '환상의 궁합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ISTP', 48, '파격적인 시너지', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ISFP', 98, '서로를 자극함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ESTP', 73, '파격적인 시너지', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFJ', 'ESFP', 64, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'INTJ', 51, '의외의 조합', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'INTP', 99, '정반대의 매력', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ENTJ', 45, '서로 배울 수 있는 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ENTP', 72, '충돌 가능성 있음', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'INFJ', 61, '의외의 조합', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'INFP', 88, '파격적인 시너지', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ENFJ', 79, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ENFP', 63, '서로를 자극함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ISTJ', 76, '환상의 궁합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ISFJ', 88, '서로를 자극함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ESTJ', 62, '충돌 가능성 있음', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ESFJ', 69, '충돌 가능성 있음', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ISTP', 55, '서로를 자극함', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ISFP', 95, '서로 배울 수 있는 관계', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ESTP', 59, '정반대의 매력', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('INFP', 'ESFP', 84, '파격적인 시너지', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'INTJ', 48, '대화가 잘 통함', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'INTP', 59, '대화가 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ENTJ', 82, '대화가 잘 통함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ENTP', 46, '환상의 궁합', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'INFJ', 74, '환상의 궁합', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'INFP', 94, '충돌 가능성 있음', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ENFJ', 81, '충돌 가능성 있음', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ENFP', 62, '안정적인 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ISTJ', 44, '대화가 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ISFJ', 87, '충돌 가능성 있음', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ESTJ', 91, '의외의 조합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ESFJ', 95, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ISTP', 89, '대화가 잘 통함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ISFP', 99, '서로 배울 수 있는 관계', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ESTP', 47, '감정적으로 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFJ', 'ESFP', 41, '서로 배울 수 있는 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'INTJ', 71, '충돌 가능성 있음', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'INTP', 50, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ENTJ', 99, '서로 배울 수 있는 관계', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ENTP', 67, '대화가 잘 통함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'INFJ', 85, '충돌 가능성 있음', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'INFP', 47, '환상의 궁합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ENFJ', 58, '서로 배울 수 있는 관계', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ENFP', 49, '의외의 조합', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ISTJ', 85, '환상의 궁합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ISFJ', 56, '감정적으로 잘 통함', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ESTJ', 96, '안정적인 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ESFJ', 82, '의외의 조합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ISTP', 55, '정반대의 매력', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ISFP', 63, '대화가 잘 통함', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ESTP', 90, '안정적인 관계', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ENFP', 'ESFP', 96, '환상의 궁합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'INTJ', 89, '정반대의 매력', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'INTP', 68, '환상의 궁합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ENTJ', 41, '정반대의 매력', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ENTP', 56, '환상의 궁합', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'INFJ', 58, '파격적인 시너지', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'INFP', 92, '환상의 궁합', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ENFJ', 97, '안정적인 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ENFP', 86, '충돌 가능성 있음', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ISTJ', 64, '안정적인 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ISFJ', 66, '환상의 궁합', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ESTJ', 73, '감정적으로 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ESFJ', 82, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ISTP', 67, '의외의 조합', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ISFP', 48, '파격적인 시너지', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ESTP', 67, '충돌 가능성 있음', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTJ', 'ESFP', 88, '대화가 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'INTJ', 61, '충돌 가능성 있음', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'INTP', 76, '안정적인 관계', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ENTJ', 88, '서로를 자극함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ENTP', 62, '대화가 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'INFJ', 95, '대화가 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'INFP', 65, '안정적인 관계', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ENFJ', 83, '감정적으로 잘 통함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ENFP', 70, '파격적인 시너지', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ISTJ', 59, '서로를 자극함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ISFJ', 73, '서로 배울 수 있는 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ESTJ', 62, '환상의 궁합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ESFJ', 63, '서로 배울 수 있는 관계', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ISTP', 74, '환상의 궁합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ISFP', 53, '의외의 조합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ESTP', 94, '파격적인 시너지', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFJ', 'ESFP', 87, '서로 배울 수 있는 관계', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'INTJ', 75, '대화가 잘 통함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'INTP', 51, '정반대의 매력', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ENTJ', 52, '충돌 가능성 있음', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ENTP', 93, '안정적인 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'INFJ', 44, '대화가 잘 통함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'INFP', 72, '대화가 잘 통함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ENFJ', 41, '안정적인 관계', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ENFP', 75, '감정적으로 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ISTJ', 48, '대화가 잘 통함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ISFJ', 53, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ESTJ', 52, '파격적인 시너지', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ESFJ', 43, '정반대의 매력', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ISTP', 60, '서로 배울 수 있는 관계', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ISFP', 92, '감정적으로 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ESTP', 83, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTJ', 'ESFP', 98, '서로 배울 수 있는 관계', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'INTJ', 51, '대화가 잘 통함', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'INTP', 77, '안정적인 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ENTJ', 51, '안정적인 관계', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ENTP', 72, '정반대의 매력', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'INFJ', 43, '환상의 궁합', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'INFP', 76, '안정적인 관계', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ENFJ', 98, '충돌 가능성 있음', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ENFP', 47, '충돌 가능성 있음', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ISTJ', 72, '정반대의 매력', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ISFJ', 43, '서로 배울 수 있는 관계', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ESTJ', 66, '파격적인 시너지', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ESFJ', 41, '파격적인 시너지', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ISTP', 67, '의외의 조합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ISFP', 91, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ESTP', 91, '감정적으로 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFJ', 'ESFP', 75, '정반대의 매력', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'INTJ', 46, '파격적인 시너지', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'INTP', 87, '정반대의 매력', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ENTJ', 94, '서로를 자극함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ENTP', 50, '충돌 가능성 있음', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'INFJ', 87, '충돌 가능성 있음', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'INFP', 70, '감정적으로 잘 통함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ENFJ', 55, '감정적으로 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ENFP', 52, '안정적인 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ISTJ', 57, '서로를 자극함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ISFJ', 58, '안정적인 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ESTJ', 73, '의외의 조합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ESFJ', 86, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ISTP', 80, '환상의 궁합', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ISFP', 94, '의외의 조합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ESTP', 53, '서로를 자극함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISTP', 'ESFP', 78, '의외의 조합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'INTJ', 95, '환상의 궁합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'INTP', 80, '감정적으로 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ENTJ', 90, '환상의 궁합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ENTP', 90, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'INFJ', 48, '안정적인 관계', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'INFP', 67, '서로를 자극함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ENFJ', 97, '충돌 가능성 있음', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ENFP', 89, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ISTJ', 57, '환상의 궁합', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ISFJ', 52, '서로 배울 수 있는 관계', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ESTJ', 45, '안정적인 관계', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ESFJ', 40, '정반대의 매력', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ISTP', 78, '대화가 잘 통함', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ISFP', 86, '감정적으로 잘 통함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ESTP', 69, '파격적인 시너지', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ISFP', 'ESFP', 82, '서로 배울 수 있는 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'INTJ', 72, '충돌 가능성 있음', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'INTP', 64, '대화가 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ENTJ', 49, '대화가 잘 통함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ENTP', 82, '의외의 조합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'INFJ', 82, '감정적으로 잘 통함', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'INFP', 67, '환상의 궁합', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ENFJ', 89, '대화가 잘 통함', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ENFP', 45, '파격적인 시너지', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ISTJ', 79, '안정적인 관계', '자유로운 성향과 규칙적인 성향이 만나 도전적인 관계가 됩니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ISFJ', 71, '환상의 궁합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ESTJ', 58, '파격적인 시너지', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ESFJ', 97, '환상의 궁합', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ISTP', 47, '서로를 자극함', '서로의 부족한 점을 보완하며 성장할 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ISFP', 49, '환상의 궁합', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ESTP', 83, '정반대의 매력', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESTP', 'ESFP', 77, '서로를 자극함', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'INTJ', 81, '서로 배울 수 있는 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'INTP', 83, '서로를 자극함', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ENTJ', 80, '감정적으로 잘 통함', '감정적인 교감이 풍부하며, 공감 능력이 뛰어난 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ENTP', 68, '감정적으로 잘 통함', '창의적인 사고와 배려가 어우러진 매력적인 조합입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'INFJ', 70, '의외의 조합', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'INFP', 71, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ENFJ', 76, '감정적으로 잘 통함', '현실적인 시선과 직관적인 사고가 만나 균형을 이룹니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ENFP', 49, '안정적인 관계', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ISTJ', 98, '파격적인 시너지', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ISFJ', 41, '서로 배울 수 있는 관계', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ESTJ', 73, '의외의 조합', '열정과 이성이 만나 강한 끌림을 만들어냅니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ESFJ', 87, '안정적인 관계', '갈등도 있지만 서로에게 배울 점이 많습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ISTP', 53, '환상의 궁합', '의사소통이 잘 되고 신뢰를 쌓기 쉬운 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ISFP', 73, '의외의 조합', '서로의 성격 차이를 존중하면 오래 갈 수 있는 좋은 관계입니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ESTP', 56, '서로 배울 수 있는 관계', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
INSERT INTO mbti (male_mbti, female_mbti, score, summary, description) VALUES ('ESFP', 'ESFP', 51, '대화가 잘 통함', '성향은 다르지만, 이해하고 노력하면 훌륭한 커플이 될 수 있습니다.');
